image: alpine:latest

Run tests:
  script:
    - apk update
    - apk add openssh
    - mkdir -p ~/.ssh
    - echo -e "$SSH_PVT_K" > ~/.ssh/id_rsa
    - chmod 600  ~/.ssh/id_rsa
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh  $EC2_INSTANCE "~/run-tests.sh"